---
- name: Setup Spark Python Environment
  hosts: all
  become: yes
  become_user: root
  vars:
    miniconda_installer: Miniconda3-py312_24.5.0-0-Linux-x86_64.sh
    miniconda_url: "https://repo.anaconda.com/miniconda/{{ miniconda_installer }}"
    miniconda_home: "/opt/miniconda3"
    conda_env_name: "spark-cassandra-python3.7"
    python_version: "3.7"

  tasks:
    - name: Check if Miniconda is already installed
      stat:
        path: "{{ miniconda_home }}/bin/conda"
      register: miniconda_check

    - name: Download Miniconda installer
      get_url:
        url: "{{ miniconda_url }}"
        dest: "/tmp/{{ miniconda_installer }}"
        mode: '0755'
      when: not miniconda_check.stat.exists

    - name: Install Miniconda
      shell: "/tmp/{{ miniconda_installer }} -b -u -p {{ miniconda_home }}"
      when: not miniconda_check.stat.exists

    - name: Disable Conda base environment auto-activation
      shell: "{{ miniconda_home }}/bin/conda config --set auto_activate_base false"

    - name: Create Conda environment with Python 3.7
      shell: "{{ miniconda_home }}/bin/conda create -n {{ conda_env_name }} python={{ python_version }} -y"
      args:
        creates: "{{ miniconda_home }}/envs/{{ conda_env_name }}"

    - name: Set permissions for Miniconda (so Spark user can read/exec)
      file:
        path: "{{ miniconda_home }}"
        mode: '0755'
        recurse: yes

    - name: Install geomet
      shell: source {{ miniconda_home }}/bin/activate {{ conda_env_name }} && pip install geomet
      args:
        executable: /bin/bash

    - name: Install cassandra-driver
      shell: source {{ miniconda_home }}/bin/activate {{ conda_env_name }} && pip install cassandra-driver==3.29.2
      args:
        executable: /bin/bash

    - name: Install mysql-connector-python
      shell: source {{ miniconda_home }}/bin/activate {{ conda_env_name }} && pip install mysql-connector-python==8.0.29
      args:
        executable: /bin/bash

    - name: Install pyspark (This might take a while)
      shell: source {{ miniconda_home }}/bin/activate {{ conda_env_name }} && pip install pyspark
      args:
        executable: /bin/bash
